name: Day Of Joy
favicon: null
layout_spectrum: 1
typography_spectrum: 0.9465674709063023
title: Day Of Joy
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.7916005451697856
  lightness: 0.726546487538144
  saturation: 0.5894193921703845
  rhythmicContrast: 0.37944372091442347
purpose: []
